# Alter Server port
server.port = 8081
  
  
  # -----------------------------------------------------------------
  
  # 		Datasource credentials
  #		JDBC Connection - MySQL
spring.datasource.url= jdbc:mysql://127.0.0.1:3306/Doctor_Patient_DB
spring.datasource.username =root
spring.datasource.password = root

spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver
#spring.datasource.driver-class-name= com.mysql.jdbc.Driver
  
  
  
  
  # Hibernate configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
  
# Used for Debugging in console
spring.jpa.show-sql=true
  
  
  
  #		Swagger configuration
  # Specify the path of the OpenAPI documentation
springdoc.api-docs.path=/api-docs
  
  # Specify the path of the Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
  
  # Enable or disable Swagger UI
springdoc.swagger-ui.enabled=true
  
  
  
 
  
  #Spring Security configuration 

logging.level.org.springframework.security=DEBUG
  
  # Spring Security Disabled - For Testing purpose
  # security.ignored=/**
  
  # Login Credentials - For Testing purpose -> Later implemented using UserDetails class
  # spring.security.user.name=Girisha 
  # spring.security.user.password=Girisha26@
  # -----------------------------------------------------------------
  
  
  # Only useful in testing - controller, not for RestControllers 
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
